name: Build and Release with Bun

on:
  # Run the workflow when a release is published or manually triggered
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Build for all architectures
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [ windows-x64, linux-x64, linux-arm64, darwin-arm64, darwin-x64 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout release tag
        run: |
          echo "Building tag: ${{ github.event.release.tag_name }}"
          git checkout ${{ github.event.release.tag_name }}
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build the project
        run: bun build --compile --target=bun-${{ matrix.platform }} ./src/index.ts --outfile dist/pagesnap
      - name: Package binary
        run: tar -czvf pagesnap-${{ matrix.platform }}.tar.gz dist/pagesnap*
      - name: Upload binaries to release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: pagesnap-${{ matrix.platform }}.tar.gz
          asset_name: pagesnap-${{ github.event.release.tag_name }}-${{ matrix.platform }}.tar.gz
          asset_content_type: application/tar+gzip