name: Build and Release with Bun

on:
  # Run the workflow when a release is published or manually triggered
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  release:
    name: Build for all architectures
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [ windows-x64, linux-x64, linux-arm64, darwin-arm64, darwin-x64 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      # Build the project
      - name: Build the project
        run: bun build --compile --target=bun-${{ matrix.platform }} ./src/index.ts --outfile dist/pagesnap-${{ matrix.platform }}

      # Upload the build artifact for this platform
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pagesnap-${{ matrix.platform }}
          path: dist/pagesnap-${{ matrix.platform }}