name: Build and Release with Bun

on:
  # Run the workflow when a release is published or manually triggered
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  release:
    name: Build for all architectures
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include: [ windows-x64, linux-x64, linux-arm64, darwin-arm64, darwin-x64 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build the project
        run: bun build --compile --target=bun-${{ matrix.include }} ./src/index.ts --outfile pagesnap
      - name: Package binary
        run: tar -czvf pagesnap-${{ matrix.include }}.tar.gz pagesnap
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pagesnap-${{ matrix.include }}
          path: pagesnap-${{ matrix.include }}.tar.gz